spring:
   datasource:
      url=jdbc:mysql://localhost:3306/Banco_Super_Legal
      username=root
      password=No290194#

   jpa:
     hibernate:
      jdbc:
       lob:
        non_contextual_creation=true
      hibernate:
       ddl-auto=create-drop
       show-sql=true
       format_sql=true
jwt:
   secret=MYJWTSECRET
   expiration=3600000