spring:
   datasource:
      url: jdbc:mysql://localhost:3306/banco_super_legal
      username: root
      password: No290194#

jpa:
 properities:
  hibernate:
   jdbc:
    lob:
     non_contextual_creation: true
   ddl-auto: create-drop
   format_sql: true
 show-sql: true
       


jwt:
   secret=MYJWTSECRET
   expiration=3600000