#spring.datasource.url=jdbc:mysql://localhost:3306/Banco_Super_Legal
#spring.datasource.username=root
#spring.datasource.password=No290194#
#
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring:
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
#
#jwt.secret=MYJWTSECRET
#jwt.expiration=3600000